"""
User Configuration Override for JARVIS

This file was auto-generated by the setup script based on your
detected hardware and selected model preferences.

You can also edit this file manually to change model settings.
"""

def apply_user_config():
    """Apply user-selected model configuration."""
    import jarvis_config as _cfg

    # Override with user-selected models
    _cfg.MODELS["planner"] = "qwen2.5-coder:7b-instruct-q4_K_M"
    _cfg.MODELS["verifier"] = "qwen2.5-coder:7b-instruct-q4_K_M"
    _cfg.MODELS["reasoner"] = "qwen2.5-coder:7b-instruct-q4_K_M"

    # Note: MODELS["czech_gateway"] should remain as jobautomation/OpenEuroLLM-Czech:latest
